spring.application.name=grid07-assignment

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/grid07db
spring.datasource.username=grid07user
spring.datasource.password=grid07pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.jpa.properties.hibernate.jdbc.time_zone=UTC